name = "Create: Perfect World 2 - AMBX Custom"
author = "FattyMieo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e3628ab2669f67cbba621ec4b9140b130ac89b2304bf5ba3ec120275d9a7362"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
